/* Writes data/stars.js for the sky page from the data of d3-celestial (github.com/ofrohn/d3-celestial,
 * BSD 3-Clause), which it doesn't keep: download its data folder's stars.6.json,
 * starnames.json, constellations.json and constellations.lines.json, then
 *   node tools/build-stars.js path/to/those/files
 * Keeps stars to magnitude 5.5 (and any fainter one a constellation figure uses), their IAU
 * proper names, and the figures as pairs of stars. Positions J2000, in degrees.
 */
const fs = require("node:fs");
const path = require("node:path");

const dir = process.argv[2];
if (!dir) { console.error("usage: node tools/build-stars.js <d3-celestial data folder>"); process.exit(1); }
const read = (f) => JSON.parse(fs.readFileSync(path.join(dir, f), "utf8"));
const catalogue = read("stars.6.json"), names = read("starnames.json");
const figures = read("constellations.lines.json"), constellations = read("constellations.json");

const LIMIT = 5.5;
const ra = ([lon]) => (lon + 360) % 360; // GeoJSON longitude −180…180 → right ascension 0…360°
const all = catalogue.features.map((f) => ({ hip: f.id, ra: ra(f.geometry.coordinates), dec: f.geometry.coordinates[1], mag: f.properties.mag, bv: Number(f.properties.bv) }));

// the star at a figure's corner: the nearest in the catalogue (they're the same coordinates); a
// corner with none is a star fainter than magnitude 6 when catalogued (Mira, a variable), kept
// as a faint point
const sep = (a, b) => {
	const d = Math.PI / 180;
	const c = Math.sin(a.dec * d) * Math.sin(b.dec * d) + Math.cos(a.dec * d) * Math.cos(b.dec * d) * Math.cos((a.ra - b.ra) * d);
	return Math.acos(Math.min(1, Math.max(-1, c))) / d;
};
const nearest = (p) => {
	let best = null, bd = Infinity;
	for (const s of all) { const d = sep(p, s); if (d < bd) { bd = d; best = s; } }
	if (bd <= 0.05) return best;
	const faint = { hip: `corner ${p.ra.toFixed(3)},${p.dec.toFixed(3)}`, ra: p.ra, dec: p.dec, mag: 6, bv: NaN };
	console.warn(`no catalogued star at ${p.ra.toFixed(3)}, ${p.dec.toFixed(3)}: kept at magnitude 6`);
	all.push(faint);
	return faint;
};

const segments = []; // [abbr, hipA, hipB]
for (const f of figures.features) {
	for (const line of f.geometry.coordinates) {
		const stars = line.map(([lon, lat]) => nearest({ ra: ra([lon]), dec: lat }));
		for (let k = 1; k < stars.length; k++) if (stars[k].hip !== stars[k - 1].hip) segments.push([f.id, stars[k - 1].hip, stars[k].hip]);
	}
}
const inFigures = new Set(segments.flatMap(([, a, b]) => [a, b]));

// the stars kept, brightest first
const kept = all.filter((s) => s.mag <= LIMIT || inFigures.has(s.hip)).sort((a, b) => a.mag - b.mag);
const index = new Map(kept.map((s, i) => [s.hip, i]));

const round = (v, n) => Number(v.toFixed(n));
const stars = kept.map((s) => [round(s.ra, 4), round(s.dec, 4), round(s.mag, 2), Number.isFinite(s.bv) ? round(s.bv, 2) : null]);
const starNames = {};
for (const s of kept) {
	const n = names[s.hip] && names[s.hip].name;
	if (n && !(n in starNames)) starNames[n] = index.get(s.hip);
}
const nameOf = Object.fromEntries(constellations.features.map((c) => [c.id, c.properties.name]));
const byFigure = new Map();
for (const [abbr, a, b] of segments) {
	if (!byFigure.has(abbr)) byFigure.set(abbr, []);
	byFigure.get(abbr).push([index.get(a), index.get(b)]);
}
const figureList = [...byFigure].map(([abbr, lines]) => ({ abbr, name: nameOf[abbr] || abbr, lines }));

const licence = fs.readFileSync(path.join(dir, "LICENSE"), "utf8").trim().split("\n").map((l) => ` * ${l}`.trimEnd()).join("\n");
const out = `/* Stars (to magnitude ${LIMIT}, and those the figures use), their IAU names, and the constellation
 * figures, for the sky page. Generated by tools/build-stars.js from the data of d3-celestial by
 * Olaf Frohn (github.com/ofrohn/d3-celestial): stars from XHIP (Anderson & Francis 2012), names
 * from the VizieR cross-indexes, figures from the IAU's constellation charts with changes by him.
 *   stars    [RA, Dec (J2000, degrees), V magnitude, B − V], brightest first
 *   names    IAU proper name → index in stars
 *   figures  { abbr, name, lines: [[star, star], …] }
 * Do not edit by hand. d3-celestial's licence:
 *
${licence}
 */
(function (root) {
	const STARS = ${JSON.stringify({ stars, names: starNames, figures: figureList })};
	root.ChaosStars = STARS;
	if (typeof module !== "undefined") module.exports = STARS;
})(typeof window !== "undefined" ? window : globalThis);
`;
fs.writeFileSync(path.join(__dirname, "..", "data", "stars.js"), out);
console.log(`${stars.length} stars, ${Object.keys(starNames).length} names, ${figureList.length} figures, ${segments.length} lines: ${(out.length / 1024).toFixed(0)} KB`);
